version: "3.7"
services:
  api:
    build: .
    image: tarpaulin-image-api
    restart: always
    ports:
      - 8000:8000
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "3309:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
      - ./mongo-data:/data/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  redis:
    image: "bitnami/redis:latest"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=po123

volumes:
  mysql-data:
    name: tarpaulin-mysql-data
  mongo-data:
    name: tarpaulin-mongodb-data
